# Generated by Django 3.2.7 on 2021-09-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eco_class_coeffs', models.TextField(default='{"euro1": 1.0, "euro2": 1.0, "euro3": 1.0, "euro4": 1.0, "euro5": 1.0, "euro6": 1.0, "electro": 1.0, "hybrid": 1.0}')),
                ('car_discount', models.FloatField(default=0)),
                ('flat_discount', models.FloatField(default=0)),
            ],
        ),
    ]
